Repository Milkshak3s/CSEC-380-G5, pull requests merged in 2019-09, with the labels that each got.

#11 Docs: Add url of github repo to answers
  docs/Activity1_Answers.md
Labels: documentation

#25 Docs: Answer question about how epics were broken down
  docs/Activity1_Answers.md
Labels: documentation

#27 Docs: Define sprint length
  docs/Activity1_Answers.md
Labels: documentation

#29 Docs: Define how projects are broken up
  docs/Activity1_Answers.md
Labels: documentation

#30 Docs: Define how security will be tested at certain points
  docs/Activity1_Answers.md
Labels: documentation

#31 Docs: Defined security testing we'd do in an ideal world
  docs/Activity1_Answers.md
Labels: documentation

#26 added dummy frontend and test
  server/frontend/Dockerfile
  server/frontend/index.html
  tests/requirements.txt
  tests/test_helloworld.py
Labels: enhancement

#32 DevOps: Setup travis tests
  .gitignore
  .travis.yml
Labels: enhancement

#28 Docs: Setup an agile process for project development
  docs/Activity1_Answers.md
  docs/Agile_Plan.md
Labels: documentation

#36 Docs: Add site mockups
  .gitignore
  docs/csec_380_mockup.pdf
Labels: documentation

#38 Add UML flow diagram for user interaction
  docs/Web-UML-Flow-Diagram.jpg
Labels: documentation

#35 Added network topology
  docs/380_project_network_topology3.PNG
Labels: documentation

#37 Added db scheme and use case UML diagram
  docs/db_scheme.PNG
  docs/use_cases_UML.PNG
Labels: documentation

#40 Created Activity2 answers
  docs/Activity2_Answers.md
Labels: documentation

#62 Feature: Add mysql server to docker-compose
  docker-compose.yml
Labels: enhancement

#63 Feature: Add frontend to docker setup
  docker-compose.yml
  frontend/.gitignore
  frontend/Dockerfile
  frontend/README.md
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/serviceWorker.js
  frontend/yarn.lock
Labels: enhancement

#64 Feature: Basic login frontend
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/LoginForm.js
  frontend/src/scenes/AppLogin.js
  frontend/yarn.lock
Labels: enhancement

#68 Feature: Backend API
  .gitignore
  backend/Dockerfile
  backend/__pycache__/app.cpython-37.pyc
  backend/app.cfg
  backend/app.py
  backend/requirements.txt
  docker-compose.yml
Labels: enhancement, help wanted
